# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
INCLUDES += -I../crashpad/build/crashpad -I../crashpad/build/crashpad/third_party/mini_chromium/mini_chromium -I../crashpad/build/crashpad/compat/mac -I../crashpad/build/crashpad/compat/non_win -I../crashpad/build/crashpad/compat/non_elf
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
ALL_LDFLAGS += $(LDFLAGS)
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/libcrashpad_snapshot.a
OBJDIR = obj/Release/crashpad_snapshot
DEFINES += -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -g -mmacosx-version-min=10.9
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -g -std=c++14 -mmacosx-version-min=10.9

else ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/libcrashpad_snapshot.a
OBJDIR = obj/Debug/crashpad_snapshot
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -fPIC -g -mmacosx-version-min=10.9
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -fPIC -g -std=c++14 -mmacosx-version-min=10.9

else
  $(error "invalid configuration $(config)")
endif

# Per File Configurations
# #############################################


# File sets
# #############################################

OBJECTS :=

OBJECTS += $(OBJDIR)/annotation_snapshot.o
OBJECTS += $(OBJDIR)/capture_memory.o
OBJECTS += $(OBJDIR)/cpu_context.o
OBJECTS += $(OBJDIR)/cpu_context_mac.o
OBJECTS += $(OBJDIR)/cpuid_reader.o
OBJECTS += $(OBJDIR)/crashpad_info_client_options.o
OBJECTS += $(OBJDIR)/custom.o
OBJECTS += $(OBJDIR)/exception_snapshot_mac.o
OBJECTS += $(OBJDIR)/exception_snapshot_minidump.o
OBJECTS += $(OBJDIR)/handle_snapshot.o
OBJECTS += $(OBJDIR)/mach_o_image_annotations_reader.o
OBJECTS += $(OBJDIR)/mach_o_image_reader.o
OBJECTS += $(OBJDIR)/mach_o_image_segment_reader.o
OBJECTS += $(OBJDIR)/mach_o_image_symbol_table_reader.o
OBJECTS += $(OBJDIR)/memory_snapshot.o
OBJECTS += $(OBJDIR)/memory_snapshot_minidump.o
OBJECTS += $(OBJDIR)/minidump_annotation_reader.o
OBJECTS += $(OBJDIR)/minidump_context_converter.o
OBJECTS += $(OBJDIR)/minidump_simple_string_dictionary_reader.o
OBJECTS += $(OBJDIR)/minidump_string_list_reader.o
OBJECTS += $(OBJDIR)/minidump_string_reader.o
OBJECTS += $(OBJDIR)/module_snapshot_mac.o
OBJECTS += $(OBJDIR)/module_snapshot_minidump.o
OBJECTS += $(OBJDIR)/process_reader_mac.o
OBJECTS += $(OBJDIR)/process_snapshot_mac.o
OBJECTS += $(OBJDIR)/process_snapshot_minidump.o
OBJECTS += $(OBJDIR)/process_types.o
OBJECTS += $(OBJDIR)/system_snapshot_mac.o
OBJECTS += $(OBJDIR)/system_snapshot_minidump.o
OBJECTS += $(OBJDIR)/thread_snapshot_mac.o
OBJECTS += $(OBJDIR)/thread_snapshot_minidump.o
OBJECTS += $(OBJDIR)/timezone.o
OBJECTS += $(OBJDIR)/unloaded_module_snapshot.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking crashpad_snapshot
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning crashpad_snapshot
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/annotation_snapshot.o: ../crashpad/build/crashpad/snapshot/annotation_snapshot.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/capture_memory.o: ../crashpad/build/crashpad/snapshot/capture_memory.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cpu_context.o: ../crashpad/build/crashpad/snapshot/cpu_context.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crashpad_info_client_options.o: ../crashpad/build/crashpad/snapshot/crashpad_info_client_options.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_snapshot.o: ../crashpad/build/crashpad/snapshot/handle_snapshot.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cpu_context_mac.o: ../crashpad/build/crashpad/snapshot/mac/cpu_context_mac.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/exception_snapshot_mac.o: ../crashpad/build/crashpad/snapshot/mac/exception_snapshot_mac.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mach_o_image_annotations_reader.o: ../crashpad/build/crashpad/snapshot/mac/mach_o_image_annotations_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mach_o_image_reader.o: ../crashpad/build/crashpad/snapshot/mac/mach_o_image_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mach_o_image_segment_reader.o: ../crashpad/build/crashpad/snapshot/mac/mach_o_image_segment_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mach_o_image_symbol_table_reader.o: ../crashpad/build/crashpad/snapshot/mac/mach_o_image_symbol_table_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/module_snapshot_mac.o: ../crashpad/build/crashpad/snapshot/mac/module_snapshot_mac.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/process_reader_mac.o: ../crashpad/build/crashpad/snapshot/mac/process_reader_mac.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/process_snapshot_mac.o: ../crashpad/build/crashpad/snapshot/mac/process_snapshot_mac.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/process_types.o: ../crashpad/build/crashpad/snapshot/mac/process_types.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/custom.o: ../crashpad/build/crashpad/snapshot/mac/process_types/custom.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/system_snapshot_mac.o: ../crashpad/build/crashpad/snapshot/mac/system_snapshot_mac.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/thread_snapshot_mac.o: ../crashpad/build/crashpad/snapshot/mac/thread_snapshot_mac.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/memory_snapshot.o: ../crashpad/build/crashpad/snapshot/memory_snapshot.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/exception_snapshot_minidump.o: ../crashpad/build/crashpad/snapshot/minidump/exception_snapshot_minidump.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/memory_snapshot_minidump.o: ../crashpad/build/crashpad/snapshot/minidump/memory_snapshot_minidump.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/minidump_annotation_reader.o: ../crashpad/build/crashpad/snapshot/minidump/minidump_annotation_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/minidump_context_converter.o: ../crashpad/build/crashpad/snapshot/minidump/minidump_context_converter.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/minidump_simple_string_dictionary_reader.o: ../crashpad/build/crashpad/snapshot/minidump/minidump_simple_string_dictionary_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/minidump_string_list_reader.o: ../crashpad/build/crashpad/snapshot/minidump/minidump_string_list_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/minidump_string_reader.o: ../crashpad/build/crashpad/snapshot/minidump/minidump_string_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/module_snapshot_minidump.o: ../crashpad/build/crashpad/snapshot/minidump/module_snapshot_minidump.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/process_snapshot_minidump.o: ../crashpad/build/crashpad/snapshot/minidump/process_snapshot_minidump.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/system_snapshot_minidump.o: ../crashpad/build/crashpad/snapshot/minidump/system_snapshot_minidump.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/thread_snapshot_minidump.o: ../crashpad/build/crashpad/snapshot/minidump/thread_snapshot_minidump.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/timezone.o: ../crashpad/build/crashpad/snapshot/posix/timezone.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/unloaded_module_snapshot.o: ../crashpad/build/crashpad/snapshot/unloaded_module_snapshot.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cpuid_reader.o: ../crashpad/build/crashpad/snapshot/x86/cpuid_reader.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif